dist: trusty
sudo: required

language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

notifications:
  email: false

before_install: source build_tools/travis/before_install.sh
install: source build_tools/travis/install.sh
script: RUN_DOCS=true RUN_SLOW=true RUN_FLAKE8=true bash build_tools/travis/test_script.sh
after_success: COVERAGE=true source build_tools/travis/after_success.sh
